name: Compilar LaTeX
on: [push] # Se ejecuta cada vez que subes cambios

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar el entorno
        uses: actions/checkout@v4

      - name: Compilar PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex # Cambia esto si tu archivo principal tiene otro nombre

      - name: Subir PDF como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: articulo-pdf
          path: main.pdf
